### ISSUE TITLE
submit button does not work

### ISSUE THREAD

**Issue by gandolfslayer** [Ranork/Auto-Linkedin-App#2]
upon trying to sign into the desktop app, the submit button refuses to work. i have tried to rebuild the application and automate the login process with my credentials but im not having any luck.

**Comment by Ranork** [comment]
Oh app is not runnable for now but i can logging in, you can look at this line for debug:
https://github.com/Ranork/Auto-Linkedin-App/blob/main/templates/login.html#L107
